version: '3.9'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5433:5432"
    volumes:
      - ./data_user:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=evheniy
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=user_management